"""latest migration

Revision ID: 02e5b963a6cc
Revises: 812820c518d3
Create Date: 2021-07-08 17:29:02.685874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e5b963a6cc'
down_revision = '812820c518d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('bot', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('bot', sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('category', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('category', sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'update_time')
    op.drop_column('category', 'create_time')
    op.drop_column('bot', 'update_time')
    op.drop_column('bot', 'create_time')
    op.drop_table('user')
    # ### end Alembic commands ###
