"""changed field add_by_user

Revision ID: 0a1a586e8998
Revises: f559fe2c83e4
Create Date: 2021-07-01 17:10:28.609896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1a586e8998'
down_revision = 'f559fe2c83e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bot_category_id_fkey', 'bot', type_='foreignkey')
    op.drop_constraint('bot_add_by_user_id_fkey', 'bot', type_='foreignkey')
    op.create_foreign_key(None, 'bot', 'user', ['add_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'bot', 'category', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bot', type_='foreignkey')
    op.drop_constraint(None, 'bot', type_='foreignkey')
    op.create_foreign_key('bot_add_by_user_id_fkey', 'bot', 'user', ['add_by_user_id'], ['id'])
    op.create_foreign_key('bot_category_id_fkey', 'bot', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
