"""Added Comment model

Revision ID: 1ed440064be6
Revises: f958ac70bc4d
Create Date: 2021-07-19 11:46:20.666591

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1ed440064be6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column(
            "update_time", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("to_bot", sa.Integer(), nullable=False),
        sa.Column("add_by_user", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["add_by_user"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["to_bot"], ["bot.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment")
    # ### end Alembic commands ###
