"""changed some fields name

Revision ID: 27c571b334e7
Revises: 9f23a7439c6b
Create Date: 2021-07-06 15:55:21.286717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c571b334e7'
down_revision = '9f23a7439c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['base_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=250), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['base_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('base_model', 'description')
    op.drop_column('base_model', 'author')
    op.drop_column('base_model', 'name')
    op.drop_column('base_model', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_model', sa.Column('link', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('base_model', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('base_model', sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('base_model', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_table('bot')
    op.drop_table('category')
    # ### end Alembic commands ###
