"""changed like name

Revision ID: 4003a5ab39b8
Revises: e2e6d68a51a0
Create Date: 2021-07-01 19:12:05.675086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4003a5ab39b8'
down_revision = 'e2e6d68a51a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_bot_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_bot_id'], ['bot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('to_bot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='like_author_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_bot_id'], ['bot.id'], name='like_to_bot_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='like_pkey')
    )
    op.drop_table('Like')
    # ### end Alembic commands ###
