"""created user model

Revision ID: 430aab868be1
Revises: d704e5fa4202
Create Date: 2021-07-01 19:04:45.056878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430aab868be1'
down_revision = 'd704e5fa4202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lukas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_bot_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_bot_id'], ['bot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('to_bot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='like_author_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_bot_id'], ['bot.id'], name='like_to_bot_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='like_pkey')
    )
    op.drop_table('lukas')
    # ### end Alembic commands ###
