"""empty message

Revision ID: 8259adcdf822
Revises: 4d89a34f8904
Create Date: 2021-08-31 17:59:12.158789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8259adcdf822'
down_revision = '4d89a34f8904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('add_by_user', sa.Integer(), nullable=True),
    sa.Column('s3_link', sa.String(length=100), nullable=False),
    sa.Column('glacier_link', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['add_by_user'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('glacier_link'),
    sa.UniqueConstraint('s3_link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    # ### end Alembic commands ###
