"""changed some fields name

Revision ID: 9f23a7439c6b
Revises: 1cd15bf75473
Create Date: 2021-07-06 15:35:18.231140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f23a7439c6b'
down_revision = '1cd15bf75473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('base_model_category_id_fkey', 'base_model', type_='foreignkey')
    op.drop_column('base_model', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_model', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('base_model_category_id_fkey', 'base_model', 'base_model', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
