"""Changed id field

Revision ID: b9c061d9863e
Revises:
Create Date: 2021-07-12 11:47:43.689258

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b9c061d9863e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column(
            "update_time", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column(
            "update_time", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "bot",
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column(
            "update_time", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("link", sa.String(length=250), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bot")
    op.drop_table("user")
    op.drop_table("category")
    # ### end Alembic commands ###
