"""changed like name

Revision ID: ba7071171f7c
Revises: 4003a5ab39b8
Create Date: 2021-07-01 19:14:03.022699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7071171f7c'
down_revision = '4003a5ab39b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_bot_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_bot_id'], ['bot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Like',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Like_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('to_bot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='Like_author_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_bot_id'], ['bot.id'], name='Like_to_bot_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Like_pkey')
    )
    op.drop_table('bot_like')
    # ### end Alembic commands ###
