"""changed field category_id

Revision ID: d704e5fa4202
Revises: 0a1a586e8998
Create Date: 2021-07-01 18:26:39.519395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd704e5fa4202'
down_revision = '0a1a586e8998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bot_category_id_fkey', 'bot', type_='foreignkey')
    op.drop_constraint('bot_add_by_user_id_fkey', 'bot', type_='foreignkey')
    op.create_foreign_key(None, 'bot', 'user', ['add_by_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bot', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bot', type_='foreignkey')
    op.drop_constraint(None, 'bot', type_='foreignkey')
    op.create_foreign_key('bot_add_by_user_id_fkey', 'bot', 'user', ['add_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('bot_category_id_fkey', 'bot', 'category', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
