"""added SET NULL

Revision ID: e7b80fbbdb44
Revises: fb2095cf82ab
Create Date: 2021-07-06 14:02:13.927383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b80fbbdb44'
down_revision = 'fb2095cf82ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bot_category_id_fkey', 'bot', type_='foreignkey')
    op.create_foreign_key(None, 'bot', 'category', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bot', type_='foreignkey')
    op.create_foreign_key('bot_category_id_fkey', 'bot', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
