"""added id into some fields in Bot model

Revision ID: f559fe2c83e4
Revises: c426cbe6d160
Create Date: 2021-07-01 13:41:21.878164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f559fe2c83e4'
down_revision = 'c426cbe6d160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('bot', sa.Column('add_by_user_id', sa.Integer(), nullable=True))
    op.drop_constraint('bot_category_fkey', 'bot', type_='foreignkey')
    op.drop_constraint('bot_add_by_user_fkey', 'bot', type_='foreignkey')
    op.create_foreign_key(None, 'bot', 'user', ['add_by_user_id'], ['id'])
    op.create_foreign_key(None, 'bot', 'category', ['category_id'], ['id'])
    op.drop_column('bot', 'category')
    op.drop_column('bot', 'add_by_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('add_by_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bot', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bot', type_='foreignkey')
    op.drop_constraint(None, 'bot', type_='foreignkey')
    op.create_foreign_key('bot_add_by_user_fkey', 'bot', 'user', ['add_by_user'], ['id'])
    op.create_foreign_key('bot_category_fkey', 'bot', 'category', ['category'], ['id'])
    op.drop_column('bot', 'add_by_user_id')
    op.drop_column('bot', 'category_id')
    # ### end Alembic commands ###
