"""created Base model

Revision ID: fb2095cf82ab
Revises: 856b03419a0b
Create Date: 2021-07-06 12:48:01.422966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2095cf82ab'
down_revision = '856b03419a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('bot', sa.Column('update_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('category', sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('category', sa.Column('update_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('update_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'update_date')
    op.drop_column('user', 'create_date')
    op.drop_column('category', 'update_date')
    op.drop_column('category', 'create_date')
    op.drop_column('bot', 'update_date')
    op.drop_column('bot', 'create_date')
    # ### end Alembic commands ###
